global:
  resolve_timeout: 5m

route:
  receiver: "jenkins-rollback-webhook"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m

receivers:
  - name: "jenkins-rollback-webhook"
    webhook_configs:
      - url: "http://13.53.197.43:8080/generic-webhook-trigger/invoke?token=ROLLBACK_26B6B8_TOKEN"
        http_config:
          basic_auth:
            username: "admin"
            password: "1155fe0641285071581d2b81a436096773"
        send_resolved: false
