global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'jenkins-rollback-webhook'

receivers:
- name: 'jenkins-rollback-webhook'
  webhook_configs:
  - url: 'http://16.170.222.228:8080/generic-webhook-trigger/invoke?token=ROLLBACK_26B6B8_TOKEN'
    send_resolved: true
